---
root: true
env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules: {}
ignorePatterns:
  - bin/**/*
  - dist/**/*
