---
root: true
env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.lib.json
  ecmaVersion: latest
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
rules:
  "@typescript-eslint/no-non-null-assertion": off
  simple-import-sort/imports: error
  simple-import-sort/exports: error
ignorePatterns:
  - bin/**/*
  - dist/**/*
  - src/**/*.test.ts
  - jest.config.js
