compressionLevel: 0
enableGlobalCache: false

npmScopes:
  adesso-se:
    npmPublishRegistry: "https://registry.npmjs.org"

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
